version: '3.4'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  web:
    build: .
    image: rails-on-docker:1.0.0      
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true    
    environment:
      - DATABASE_URL=postgres://postgres@db
      - WEBPACKER_DEV_SERVER_HOST=webpacker
      - HISTFILE=/usr/src/app/.dockerdev/.bash_history
    volumes:
      - .:/usr/src/app/:cached
      - bundle:/usr/local/bundle
    depends_on:
      - db
  webpacker:
    build: .
    image: rails-on-docker:1.0.0
    command: ./bin/webpack-dev-server
    ports:
      - "3035:3035"
    volumes:
      - .:/usr/src/app:cached
      - bundle:/usr/local/bundle
volumes:
  bundle:
  db_data:
