version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  web:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres@db
    depends_on:
      - db
  # webpacker:
  #   build: .
  #   env_file:
  #     - ".env.docker"
  #   command: ./bin/webpack-dev-server
  #   volumes:
  #     - .:/usr/src/app
  #   ports:
  #     - "3035:3035"

volumes:
  db-data:
    driver: local
